<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: route_guide.proto

namespace Routeguide;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 * A feature names something at a given point.
 * If a feature could not be named, the name is empty.
 * </pre>
 *
 * Protobuf type <code>routeguide.Feature</code>
 */
class Feature extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     * The name of the feature.
     * </pre>
     *
     * <code>string name = 1;</code>
     */
    private $name = '';
    /**
     * <pre>
     * The point where the feature is detected.
     * </pre>
     *
     * <code>.routeguide.Point location = 2;</code>
     */
    private $location = null;

    public function __construct() {
        \GPBMetadata\RouteGuide::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     * The name of the feature.
     * </pre>
     *
     * <code>string name = 1;</code>
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * <pre>
     * The name of the feature.
     * </pre>
     *
     * <code>string name = 1;</code>
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;
    }

    /**
     * <pre>
     * The point where the feature is detected.
     * </pre>
     *
     * <code>.routeguide.Point location = 2;</code>
     */
    public function getLocation()
    {
        return $this->location;
    }

    /**
     * <pre>
     * The point where the feature is detected.
     * </pre>
     *
     * <code>.routeguide.Point location = 2;</code>
     */
    public function setLocation(&$var)
    {
        GPBUtil::checkMessage($var, \Routeguide\Point::class);
        $this->location = $var;
    }

}

