<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: route_guide.proto

namespace Routeguide;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 * Points are represented as latitude-longitude pairs in the E7 representation
 * (degrees multiplied by 10**7 and rounded to the nearest integer).
 * Latitudes should be in the range +/- 90 degrees and longitude should be in
 * the range +/- 180 degrees (inclusive).
 * </pre>
 *
 * Protobuf type <code>routeguide.Point</code>
 */
class Point extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>int32 latitude = 1;</code>
     */
    private $latitude = 0;
    /**
     * <code>int32 longitude = 2;</code>
     */
    private $longitude = 0;

    public function __construct() {
        \GPBMetadata\RouteGuide::initOnce();
        parent::__construct();
    }

    /**
     * <code>int32 latitude = 1;</code>
     */
    public function getLatitude()
    {
        return $this->latitude;
    }

    /**
     * <code>int32 latitude = 1;</code>
     */
    public function setLatitude($var)
    {
        GPBUtil::checkInt32($var);
        $this->latitude = $var;
    }

    /**
     * <code>int32 longitude = 2;</code>
     */
    public function getLongitude()
    {
        return $this->longitude;
    }

    /**
     * <code>int32 longitude = 2;</code>
     */
    public function setLongitude($var)
    {
        GPBUtil::checkInt32($var);
        $this->longitude = $var;
    }

}

