<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: route_guide.proto

namespace Routeguide;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 * A latitude-longitude rectangle, represented as two diagonally opposite
 * points "lo" and "hi".
 * </pre>
 *
 * Protobuf type <code>routeguide.Rectangle</code>
 */
class Rectangle extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     * One corner of the rectangle.
     * </pre>
     *
     * <code>.routeguide.Point lo = 1;</code>
     */
    private $lo = null;
    /**
     * <pre>
     * The other corner of the rectangle.
     * </pre>
     *
     * <code>.routeguide.Point hi = 2;</code>
     */
    private $hi = null;

    public function __construct() {
        \GPBMetadata\RouteGuide::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     * One corner of the rectangle.
     * </pre>
     *
     * <code>.routeguide.Point lo = 1;</code>
     */
    public function getLo()
    {
        return $this->lo;
    }

    /**
     * <pre>
     * One corner of the rectangle.
     * </pre>
     *
     * <code>.routeguide.Point lo = 1;</code>
     */
    public function setLo(&$var)
    {
        GPBUtil::checkMessage($var, \Routeguide\Point::class);
        $this->lo = $var;
    }

    /**
     * <pre>
     * The other corner of the rectangle.
     * </pre>
     *
     * <code>.routeguide.Point hi = 2;</code>
     */
    public function getHi()
    {
        return $this->hi;
    }

    /**
     * <pre>
     * The other corner of the rectangle.
     * </pre>
     *
     * <code>.routeguide.Point hi = 2;</code>
     */
    public function setHi(&$var)
    {
        GPBUtil::checkMessage($var, \Routeguide\Point::class);
        $this->hi = $var;
    }

}

