<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: route_guide.proto

namespace Routeguide;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 * A RouteNote is a message sent while at a given point.
 * </pre>
 *
 * Protobuf type <code>routeguide.RouteNote</code>
 */
class RouteNote extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     * The location from which the message is sent.
     * </pre>
     *
     * <code>.routeguide.Point location = 1;</code>
     */
    private $location = null;
    /**
     * <pre>
     * The message to be sent.
     * </pre>
     *
     * <code>string message = 2;</code>
     */
    private $message = '';

    public function __construct() {
        \GPBMetadata\RouteGuide::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     * The location from which the message is sent.
     * </pre>
     *
     * <code>.routeguide.Point location = 1;</code>
     */
    public function getLocation()
    {
        return $this->location;
    }

    /**
     * <pre>
     * The location from which the message is sent.
     * </pre>
     *
     * <code>.routeguide.Point location = 1;</code>
     */
    public function setLocation(&$var)
    {
        GPBUtil::checkMessage($var, \Routeguide\Point::class);
        $this->location = $var;
    }

    /**
     * <pre>
     * The message to be sent.
     * </pre>
     *
     * <code>string message = 2;</code>
     */
    public function getMessage()
    {
        return $this->message;
    }

    /**
     * <pre>
     * The message to be sent.
     * </pre>
     *
     * <code>string message = 2;</code>
     */
    public function setMessage($var)
    {
        GPBUtil::checkString($var, True);
        $this->message = $var;
    }

}

